@startuml
title Class diagram - WMS
top to bottom direction
skinparam linetype ortho

class Administrator {
  +vytvoritPohyb()
  +spravovatSoucastky()
}

class Projekt {
  -id: int
  -nazev: String

  +priradSoucastku(s: Soucastka)
  +odeberSoucastku(s: Soucastka)
}

class Soucastka {
  -id: int
  -nazev: String
  -mnozstvi: int

  +zvysMnozstvi(pocet: int)
  +snizMnozstvi(pocet: int)
  +overDostupnost(): boolean
}

class Pohyb {
  -id: int
  -typ: String
  -datum: Date
  -stav: String

  +vytvoritPohyb()
  +schvalit()
  +provestPohyb()
}

class Sklad {
  -id: int
  -nazev: String

  +aktualizujMnozstvi()
}

class Lokace {
  -id: int
  -oznaceni: String
}

Administrator --> Pohyb
Projekt "1" --> "*" Soucastka
Soucastka "1" --> "*" Pohyb
Sklad "1" --> "*" Lokace
Lokace "1" --> "*" Soucastka

@enduml
