@startuml
hide circle

class Soucastka {
  id : int
  nazev : String
  popis : String
  partNumber : String
}

class KategorieSoucastky {
  id : int
  nazev : String
}

class Dodavatel {
  id : int
  nazev : String
  email : String
  telefon : String
}

class Sklad {
  id : int
  nazev : String
  adresa : String
}

class SkladovaLokace {
  id : int
  kodLokace : String
}

class PohybSkladu {
  id : int
  datum : Date
  mnozstvi : int
}

class Naskladneni {
  cisloDodavky : String
}

class Vyskladneni {
  duvod : String
}

class Presun {
  zdrojLokace : String
  cilLokace : String
}

class Projekt {
  id : int
  nazev : String
}

class ProjektSoucastka {
  mnozstvi : int
}

' ===== vztahy =====

KategorieSoucastky "1" -- "0..*" Soucastka : kategorie
Dodavatel "1" -- "0..*" Soucastka : dodava

Sklad "1" *-- "0..*" SkladovaLokace : obsahuje

SkladovaLokace "1" -- "0..*" Soucastka : [kodLokace]

Soucastka "1" -- "0..*" PohybSkladu : soucastka
SkladovaLokace "1" -- "0..*" PohybSkladu : lokace

PohybSkladu <|-- Naskladneni
PohybSkladu <|-- Vyskladneni
PohybSkladu <|-- Presun

Projekt "1" o-- "0..*" ProjektSoucastka : obsahuje
Soucastka "1" -- "0..*" ProjektSoucastka : komponenta

@enduml
