@startuml
title State diagram - Pohyb

[*] --> Vytvoren

Vytvoren : entry / vytvoritPohyb()

Vytvoren --> Schvalen : [data_ok]
Vytvoren --> Zamitnut : [chyba]

Schvalen : entry / schvalit()

Schvalen --> Proveden : provestPohyb()
Proveden : entry / aktualizujMnozstvi()

Proveden --> [*]
Zamitnut --> [*]

@enduml
