@startuml
scale 2
left to right direction
title State diagram - SkladovyPohyb

[*] --> Vytvoren

Vytvoren : entry / vytvoritPohyb()
Vytvoren --> Validovan : submit()

Validovan : entry / overitData()
Validovan --> Proveden_Prijem : provestPohyb() [data_platna / prijem]
Validovan --> Proveden_Vydej : provestPohyb() [data_platna / vydej]
Validovan --> Proveden_Presun : provestPohyb() [data_platna / presun]
Validovan --> Zamitnut : [neplatna_data]
Validovan --> Zamitnut : [nedostatecne_mnozstvi]

Proveden_Prijem : entry / soucastka.zvysMnozstvi()
Proveden_Vydej : entry / soucastka.snizMnozstvi()
Proveden_Presun : entry / zmenLokaci()

Proveden_Prijem --> [*]
Proveden_Vydej --> [*]
Proveden_Presun --> [*]
Zamitnut --> [*]

@enduml
