@startuml
top to bottom direction

[*] --> Vytvoren

Vytvoren : entry / vytvoritPohyb()
Vytvoren : do / čekat na odeslání
Vytvoren : exit / uložit pohyb
Vytvoren --> Validovan : Pohyb odeslán

Validovan : entry / overitData()
Validovan : do / kontrolovat data
Validovan : exit / potvrdit výsledek
Validovan --> Proveden_Prijem : Typ == příjem
Validovan --> Proveden_Vydej : Typ == výdej
Validovan --> Proveden_Presun : Typ == přesun
Validovan --> Zamitnut : Neplatná data
Validovan --> Zamitnut : Nedostatečné množství

Zamitnut : entry / zaznamenat chybu
Zamitnut : do / čekat
Zamitnut : exit / notifikovat uživatele

Proveden_Prijem : entry / soucastka.zvysMnozstvi()
Proveden_Prijem : do / aktualizovat sklad
Proveden_Prijem : exit / uložit záznam

Proveden_Vydej : entry / soucastka.snizMnozstvi()
Proveden_Vydej : do / aktualizovat sklad
Proveden_Vydej : exit / uložit záznam

Proveden_Presun : entry / zmenLokaci()
Proveden_Presun : do / aktualizovat lokaci
Proveden_Presun : exit / uložit záznam

Proveden_Prijem --> [*] : Pohyb dokončen
Proveden_Vydej --> [*] : Pohyb dokončen
Proveden_Presun --> [*] : Pohyb dokončen
Zamitnut --> [*] : Pohyb byl zamítnut

@enduml
