@startuml
top to bottom direction
title State diagram - Soucastka


[*] --> Dostupna : Přidána do systému

Dostupna : do / sledovat stav zásob
Dostupna : Naskladněno / zvysMnozstvi(pocet)
Dostupna : Rezervována / rezervovat(pocet)
Dostupna : Rezervace zrušena / zrusitRezervaci(pocet)
Dostupna --> Vydana : Vydána ze skladu
Dostupna --> Odepsana : Odepsána

Vydana : entry / snizMnozstvi()
Vydana : do / evidovat spotřebu
Vydana --> Dostupna : Vrácena na sklad
Vydana --> Odepsana : Odepsána

Odepsana --> [*] : Součástka odepsána

@enduml
