@startuml
left to right direction
title Use Case diagram - WMS

actor Administrator

rectangle WMS {

  Administrator -- (Sprava soucastek)
  Administrator -- (Vytvoreni pohybu)
  Administrator -- (Prirazeni soucastky k projektu)
  Administrator -- (Zobrazeni skladu)

  (Sprava soucastek) .> (Kontrola stavu) : <<include>>
  (Vytvoreni pohybu) .> (Kontrola dat) : <<include>>
  (Prirazeni soucastky k projektu) .> (Kontrola dostupnosti) : <<include>>

  (Vytvoreni pohybu) .> (Schvaleni pohybu) : <<extend>>

}

@enduml
