@startuml
left to right direction
title Use Case Diagram - WMS

actor Uzivatel
actor Administrator

rectangle WMS {
  
  Uzivatel -- (Vytvořit pohyb)
  Uzivatel -- (Zobrazit sklad)
  Uzivatel -- (Přiřadit součástku projektu)

  (Vytvořit pohyb) --> (Zkontrolovat data) : <<include>>
  (Přiřadit součástku projektu) --> (Zkontrolovat data) : <<include>>

  (Vytvořit pohyb) <-- (Schválit pohyb) : <<extend>> [je potřeba schválení]

  Administrator -- (Schválit pohyb)
  Administrator -- (Správa skladu)

}

@enduml
