@startuml
skinparam defaultFontSize 13
skinparam ActivityBorderThickness 1.5
skinparam ArrowThickness 1.5
skinparam ActivityDiamondBorderThickness 1.5

start

:Uživatel zadá typ pohybu, součástku a množství;

:vytvoritPohyb();

:overitData();

if (Data platná?) then (ano)

  fork
    :zvysMnozstvi(pocet);
    note left: typ == příjem
  fork again
    :snizMnozstvi(pocet);
    note right: typ == výdej
  fork again
    :overDostupnost()\nzmenLokaci();
    note right: typ == přesun
  end fork

  :Pohyb potvrzen;

else (ne)
  :Pohyb zamítnut;
endif

stop
@enduml
