@startuml
title Activity diagram - Vytvoreni pohybu

start

:Zadat data;
:Kontrola dat;

if (Data OK?) then (ano)
  :Schvaleni;

  if (Schvaleno?) then (ano)
    :Provedeni pohybu;
    :Aktualizace skladu;
    :Potvrzeni;
  else (ne)
    :Zamitnuto;
  endif

else (ne)
  :Oprava dat;
  :Kontrola dat;
endif

stop

@enduml
