@startuml

actor Uzivatel
participant SkladovyPohyb
participant Soucastka

Uzivatel -> SkladovyPohyb : vytvoritPohyb()
SkladovyPohyb -> SkladovyPohyb : overitData()

alt [data OK]
    alt [typ == příjem]
        SkladovyPohyb -> Soucastka : zvysMnozstvi(pocet)
    else [typ == výdej]
        SkladovyPohyb -> Soucastka : snizMnozstvi(pocet)
    else [typ == přesun]
        SkladovyPohyb -> SkladovyPohyb : zmenLokaci()
    end
    SkladovyPohyb --> Uzivatel : pohyb potvrzen
else [data NOK]
    SkladovyPohyb --> Uzivatel : pohyb zamítnut
end

@enduml
